/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import javax.swing.JOptionPane;

/**
 *
 * @author exbex
 */
public class Corte extends javax.swing.JFrame {
    
    double num = 0.0;
    
    /**
     * Creates new form Corte
     */
    public Corte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTFCantidad = new javax.swing.JTextField();
        JBVentas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JLTotalVendido = new javax.swing.JLabel();
        FondoBlancoCi = new javax.swing.JLabel();
        FondoBlancoAp = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel3.setText("Abrir Caja");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 191, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel2.setText("Corte de Caja");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 629, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel1.setText("Monto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 334, 130, 50));

        JTFCantidad.setBackground(new java.awt.Color(155, 164, 180));
        JTFCantidad.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        JTFCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCantidadActionPerformed(evt);
            }
        });
        JTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCantidadKeyTyped(evt);
            }
        });
        getContentPane().add(JTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 334, 280, 58));

        JBVentas.setBackground(new java.awt.Color(61, 199, 105));
        JBVentas.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBVentas.setText("Ir a Ventas");
        JBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVentasActionPerformed(evt);
            }
        });
        getContentPane().add(JBVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 308, 260, 120));

        jButton1.setBackground(new java.awt.Color(204, 17, 17));
        jButton1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jButton1.setText("Cerrar Caja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 746, 260, 120));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel4.setText("Vendido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 772, -1, -1));

        JLTotalVendido.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JLTotalVendido.setText("0.0");
        JLTotalVendido.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JLTotalVendidoPropertyChange(evt);
            }
        });
        getContentPane().add(JLTotalVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 772, 100, -1));

        FondoBlancoCi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Corte de Caja.png"))); // NOI18N
        getContentPane().add(FondoBlancoCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 590, -1, -1));

        FondoBlancoAp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Corte de Caja.png"))); // NOI18N
        getContentPane().add(FondoBlancoAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 152, -1, -1));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Azul.jpg"))); // NOI18N
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVentasActionPerformed
        Venta v = new Venta();
        v.setVisible(true);
        Venta.JLInicial.setText(String.valueOf(JTFCantidad.getText()));
        dispose();
    }//GEN-LAST:event_JBVentasActionPerformed

    private void JLTotalVendidoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JLTotalVendidoPropertyChange

    }//GEN-LAST:event_JLTotalVendidoPropertyChange

    private void JTFCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCantidadActionPerformed
        
    }//GEN-LAST:event_JTFCantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCantidadKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != ' ')) evt.consume();
    }//GEN-LAST:event_JTFCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Corte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Corte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoBlancoAp;
    private javax.swing.JLabel FondoBlancoCi;
    private javax.swing.JButton JBVentas;
    public static javax.swing.JLabel JLTotalVendido;
    public static javax.swing.JTextField JTFCantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
