/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.lang.Byte;

/**
 *
 * @author exbex
 */
public class Marcas extends javax.swing.JFrame {

    /**
     * Creates new form Marcas
     */
    public Marcas() {
        initComponents();
        JTFIDMarca.setVisible(false);
        cargarTabla();
        llenarComboBoxProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JBRegistrar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBInactivar = new javax.swing.JButton();
        JBModificar = new javax.swing.JButton();
        JTFIDMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JCBEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListado = new javax.swing.JTable();
        JCBProveedores = new javax.swing.JComboBox<>();
        FondoBlanco = new javax.swing.JLabel();
        FondoBlancoLista = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel1.setText("Registrar Marca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 236, -1, -1));

        JBRegistrar.setBackground(new java.awt.Color(20, 39, 78));
        JBRegistrar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBRegistrar.setText("Registrar");
        JBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(JBRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1156, 725, 260, 120));

        JBCancelar.setBackground(new java.awt.Color(215, 80, 56));
        JBCancelar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1466, 725, 260, 120));

        JBInactivar.setBackground(new java.awt.Color(204, 17, 17));
        JBInactivar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBInactivar.setText("Inactivar");
        JBInactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBInactivarActionPerformed(evt);
            }
        });
        getContentPane().add(JBInactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 840, 260, 120));

        JBModificar.setBackground(new java.awt.Color(57, 72, 103));
        JBModificar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBModificar.setText("Modificar");
        JBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarActionPerformed(evt);
            }
        });
        getContentPane().add(JBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 840, 260, 120));
        getContentPane().add(JTFIDMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1900, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel2.setText("Marca:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 355, -1, -1));

        JTFMarca.setBackground(new java.awt.Color(155, 164, 180));
        JTFMarca.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        JTFMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFMarcaKeyTyped(evt);
            }
        });
        getContentPane().add(JTFMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1186, 340, 443, 78));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel3.setText("Estado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 485, -1, -1));

        JCBEstado.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        JCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));
        JCBEstado.setSelectedIndex(1);
        JCBEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(JCBEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1186, 469, 443, 78));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel4.setText("Proveedor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 613, -1, -1));

        JTListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTListado.setPreferredSize(new java.awt.Dimension(611, 710));
        JTListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTListado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 116, 550, 680));

        JCBProveedores.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        getContentPane().add(JCBProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1186, 597, 443, 78));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Marca.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 190, -1, -1));

        FondoBlancoLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Lista - Marca.png"))); // NOI18N
        getContentPane().add(FondoBlancoLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Azul.jpg"))); // NOI18N
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegistrarActionPerformed
        String marca = JTFMarca.getText();
        byte estado = (byte) JCBEstado.getSelectedIndex();
        int idproveedor = JCBProveedores.getSelectedIndex() + 1;
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Marcas (Marca, Estado, FIDProveedor) VALUES (?, ?, ?)");
            ps.setString(1, marca);
            ps.setByte(2, estado);
            ps.setInt(3, idproveedor);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Marca Guardado");
            limpiar();
            cargarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_JBRegistrarActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        RegistroProductos rp = new RegistroProductos();
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarActionPerformed
        int id = Integer.parseInt(JTFIDMarca.getText());
        String marca = JTFMarca.getText();
        byte estado = (byte) JCBEstado.getSelectedIndex();
      
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Marcas SET Marca = ?, Estado = ? WHERE IDMarca = ?");
            ps.setString(1, marca);
            ps.setByte(2, estado);
            ps.setInt(3, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Marca Modificado");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBModificarActionPerformed

    private void JTListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTListadoMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        try {
            int fila = JTListado.getSelectedRow();
            int id = Integer.parseInt(JTListado.getValueAt(fila, 0).toString());
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDMarca, Marca, Estado FROM Marcas WHERE IDMarca = ?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while(rs.next()){
                JTFIDMarca.setText(String.valueOf(id));
                JTFMarca.setText(rs.getString("Marca"));
                JCBEstado.setSelectedIndex(rs.getByte("Estado"));
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_JTListadoMouseClicked

    private void JBInactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBInactivarActionPerformed
        int id = Integer.parseInt(JTFIDMarca.getText());
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Marcas SET Estado = 0 WHERE IDMarca = ?");
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Marca Inactivada");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBInactivarActionPerformed

    private void JTFMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFMarcaKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) evt.consume();
    }//GEN-LAST:event_JTFMarcaKeyTyped

    private void limpiar() {
        JTFMarca.setText("");
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) JTListado.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDMarca, Marca, Estado FROM Marcas");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; ++i){
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void llenarComboBoxProveedores() {
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT NombreProveedor FROM Proveedores");
            rs = ps.executeQuery();
            while (rs.next()) {
                String proveedor = rs.getString("NombreProveedor");
                JCBProveedores.addItem(proveedor);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBlancoLista;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBInactivar;
    private javax.swing.JButton JBModificar;
    private javax.swing.JButton JBRegistrar;
    private javax.swing.JComboBox<String> JCBEstado;
    private javax.swing.JComboBox<String> JCBProveedores;
    private javax.swing.JTextField JTFIDMarca;
    private javax.swing.JTextField JTFMarca;
    private javax.swing.JTable JTListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
