/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesusemmanuel
 */
public class Menu extends javax.swing.JFrame {

    DefaultTableModel modeloTabla = new DefaultTableModel();
    public Menu() {
        initComponents();
        cargarTabla();
        txtId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JButton();
        btnAgendarPago = new javax.swing.JButton();
        btnCompraProveedor = new javax.swing.JButton();
        btnCorteCaja = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnRegistroProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        FondoBlancoLP = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pencil.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 320, 280));

        btnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuario.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user2.png"))); // NOI18N
        btnUsuario.setText("<html>Registro de\n<br>\nUsuarios\n<html/>");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 40, 430, 300));

        btnAgendarPago.setBackground(new java.awt.Color(255, 255, 255));
        btnAgendarPago.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnAgendarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar.png"))); // NOI18N
        btnAgendarPago.setText("<html>    Agendar <br> Pago <html/>");
        btnAgendarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarPagoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgendarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 40, 430, 300));

        btnCompraProveedor.setBackground(new java.awt.Color(255, 255, 255));
        btnCompraProveedor.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnCompraProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accounting.png"))); // NOI18N
        btnCompraProveedor.setText("<html>Compra a\n<br>\nProveedor\n<html/>");
        btnCompraProveedor.setPreferredSize(new java.awt.Dimension(377, 73));
        btnCompraProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompraProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 40, 430, 300));

        btnCorteCaja.setBackground(new java.awt.Color(255, 255, 255));
        btnCorteCaja.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnCorteCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash-register.png"))); // NOI18N
        btnCorteCaja.setText("Caja");
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCorteCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(1445, 390, 430, 300));

        btnSalir.setBackground(new java.awt.Color(215, 80, 56));
        btnSalir.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 920, 260, 120));

        btnVenta.setBackground(new java.awt.Color(255, 255, 255));
        btnVenta.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/barcode.png"))); // NOI18N
        btnVenta.setText("<html>Punto de\n<br>\nVenta\n<html/>");
        btnVenta.setActionCommand("Punto de Venta\n");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 390, 430, 300));

        btnInventario.setBackground(new java.awt.Color(255, 255, 255));
        btnInventario.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnInventario.setText("<html>Reporte de  <br> Inventario <html/>");
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 740, 430, 290));

        tblPagos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Monto", "Fecha", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPagos.setRowHeight(40);
        tblPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPagosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPagos);
        if (tblPagos.getColumnModel().getColumnCount() > 0) {
            tblPagos.getColumnModel().getColumn(0).setMinWidth(0);
            tblPagos.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblPagos.getColumnModel().getColumn(0).setMaxWidth(0);
            tblPagos.getColumnModel().getColumn(3).setPreferredWidth(6);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 400, 520));

        jButton1.setBackground(new java.awt.Color(61, 199, 105));
        jButton1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jButton1.setText("Pagado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 940, 230, 70));

        btnRegistroProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistroProductos.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnRegistroProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/box.png"))); // NOI18N
        btnRegistroProductos.setText("<html>Registro de <br> Productos <html/>");
        btnRegistroProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 740, 430, 300));

        btnProveedores.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedores.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventory.png"))); // NOI18N
        btnProveedores.setText("<html>Registro de\n<br>\nProveedores\n<html/>");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 390, 430, 300));

        FondoBlancoLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Pagos - Menu.png"))); // NOI18N
        getContentPane().add(FondoBlancoLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 42, -1, -1));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Azul.jpg"))); // NOI18N
        FondoAzul.setText("jLabel1");
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1920, 1080));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        // TODO add your handling code here:
        Corte frame = new Corte();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    private void btnCompraProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraProveedorActionPerformed
        // TODO add your handling code here:
        Compras frame = new Compras();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCompraProveedorActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:
        ReporteInventario frame = new ReporteInventario();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        Venta frame = new Venta();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnAgendarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarPagoActionPerformed
        // TODO add your handling code here:
        AgendarPago frame = new AgendarPago();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAgendarPagoActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        Proveedores frame = new Proveedores();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnRegistroProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroProductosActionPerformed
        // TODO add your handling code here:
        RegistroProductos frame = new RegistroProductos();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistroProductosActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
  
        Usuario frame = new Usuario();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DateTimeFormatter dia = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        //DateTimeFormatter reloj = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime ahora = LocalDateTime.now();
        String Fecha = dia.format(ahora);    
        byte Estado = 1;
        int id = Integer.parseInt(txtId.getText());
        
        try{
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Pagos SET Estado=?, FechaReal=? WHERE IDPago=?");
            ps.setByte(1,Estado);
            ps.setString(2,Fecha);
            ps.setInt(3, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "PAGO REALIZADO");
            cargarTabla();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPagosMouseClicked
        try{
            int fila = tblPagos.getSelectedRow();
            int id = Integer.parseInt(tblPagos.getValueAt(fila,0).toString());
            PreparedStatement ps;
            ResultSet rs;
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDPago FROM Pagos WHERE IDPago =?");
            ps.setInt(1,id);
            rs = ps.executeQuery();
            
            while(rs.next()){
                txtId.setText(String.valueOf(id));
                
            }
         
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tblPagosMouseClicked

    private void cargarTabla(){
        modeloTabla = (DefaultTableModel) tblPagos.getModel();
        modeloTabla.setRowCount(0);
        
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        int[] anchos = {5,80,60,80,5};
        for(int j = 0; j< tblPagos.getColumnCount(); j++){
            tblPagos.getColumnModel().getColumn(j).setPreferredWidth(anchos[j]);
        }
        
        try{
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDPago, Descripcion, Monto, Fecha, Estado FROM Pagos Where Estado = 0" );
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; i++){
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoBlancoLP;
    private javax.swing.JButton btnAgendarPago;
    private javax.swing.JButton btnCompraProveedor;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnRegistroProductos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPagos;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
