
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author exbex
 */
public class RegistroProductos extends javax.swing.JFrame{
    
    /**
     * Creates new form RegistroProveedores
     */
    public RegistroProductos() {
        initComponents();
        JTFIDProducto.setVisible(false);
        setLocationRelativeTo(null);
        cargarTabla();
        llenarComboBoxMarcas();
        llenarComboBoxMedidas();
    }
    
    public void habilitarRegistrar(){
        if(!JTFNombreProducto.getText().isEmpty() && !JTFPrecioVenta.getText().isEmpty() && !JTFCantidad.getText().isEmpty()) {
            JBRegistrar.setEnabled(true);
        } else {
            JBRegistrar.setEnabled(false);
        }
    }
    
    public void habilitarModificar(){
        if(!JTFNombreProducto.getText().isEmpty() && !JTFPrecioVenta.getText().isEmpty() && !JTFCantidad.getText().isEmpty()) {
            JBModificar.setEnabled(true);
        } else {
            JBModificar.setEnabled(false);
        }
    }
    
    public void habilitarEliminar(){
        if(!JTFNombreProducto.getText().isEmpty() && !JTFPrecioVenta.getText().isEmpty() && !JTFCantidad.getText().isEmpty()) {
            JBEliminar.setEnabled(true);
        } else {
            JBEliminar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBModificar = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        JBRegistrar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JTFIDProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JTFNombreProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFPrecioVenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JCBMedidas = new javax.swing.JComboBox<>();
        JBMedidas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JCBMarcas = new javax.swing.JComboBox<>();
        JBAgregarMarca = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListado = new javax.swing.JTable();
        FondoBlancoFormulario = new javax.swing.JLabel();
        FondoBlancoLista = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(57, 72, 103));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBModificar.setBackground(new java.awt.Color(57, 72, 103));
        JBModificar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBModificar.setText("Modificar");
        JBModificar.setEnabled(false);
        JBModificar.setPreferredSize(new java.awt.Dimension(260, 120));
        JBModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JBModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JBModificarMouseExited(evt);
            }
        });
        JBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarActionPerformed(evt);
            }
        });
        getContentPane().add(JBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 860, 260, 120));

        JBEliminar.setBackground(new java.awt.Color(204, 17, 17));
        JBEliminar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBEliminar.setText("Eliminar");
        JBEliminar.setEnabled(false);
        JBEliminar.setPreferredSize(new java.awt.Dimension(260, 120));
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(JBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 860, 260, 120));

        JBRegistrar.setBackground(new java.awt.Color(20, 39, 78));
        JBRegistrar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBRegistrar.setText("Registrar");
        JBRegistrar.setEnabled(false);
        JBRegistrar.setPreferredSize(new java.awt.Dimension(260, 120));
        JBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(JBRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 874, 260, 120));

        JBCancelar.setBackground(new java.awt.Color(215, 80, 56));
        JBCancelar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.setPreferredSize(new java.awt.Dimension(260, 120));
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 874, 260, 120));
        getContentPane().add(JTFIDProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 110, 20, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel1.setText("Registro de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 116, -1, -1));

        JTFNombreProducto.setBackground(new java.awt.Color(155, 164, 180));
        JTFNombreProducto.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        JTFNombreProducto.setPreferredSize(new java.awt.Dimension(500, 78));
        JTFNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreProductoActionPerformed(evt);
            }
        });
        JTFNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNombreProductoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFNombreProductoKeyReleased(evt);
            }
        });
        getContentPane().add(JTFNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 219, 500, 78));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel2.setText("Nombre del Producto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 235, 390, 40));

        JTFPrecioVenta.setBackground(new java.awt.Color(155, 164, 180));
        JTFPrecioVenta.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        JTFPrecioVenta.setPreferredSize(new java.awt.Dimension(500, 78));
        JTFPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFPrecioVentaKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFPrecioVentaKeyReleased(evt);
            }
        });
        getContentPane().add(JTFPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 347, 500, 78));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel3.setText("Precio de Venta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 363, -1, -1));

        JTFCantidad.setBackground(new java.awt.Color(155, 164, 180));
        JTFCantidad.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        JTFCantidad.setPreferredSize(new java.awt.Dimension(500, 78));
        JTFCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCantidadKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTFCantidadKeyReleased(evt);
            }
        });
        getContentPane().add(JTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 475, 500, 78));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 491, -1, -1));

        JCBMedidas.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        getContentPane().add(JCBMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 603, 200, 78));

        JBMedidas.setBackground(new java.awt.Color(61, 199, 105));
        JBMedidas.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBMedidas.setText("Agregar");
        JBMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMedidasActionPerformed(evt);
            }
        });
        getContentPane().add(JBMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1612, 603, 200, 78));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel6.setText("Unidad de Medida:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 619, -1, -1));

        JCBMarcas.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        getContentPane().add(JCBMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 731, 200, 78));

        JBAgregarMarca.setBackground(new java.awt.Color(61, 199, 105));
        JBAgregarMarca.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBAgregarMarca.setText("Agregar");
        JBAgregarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(JBAgregarMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1612, 731, 200, 78));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel7.setText("Marca:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 747, -1, -1));

        JTListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Precio de Venta", "Cantidad", "Unidad de Medida", "Marcal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTListado.setPreferredSize(new java.awt.Dimension(611, 710));
        JTListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTListadoMouseClicked(evt);
            }
        });
        JTListado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTListadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTListadoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(JTListado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 560, 710));

        FondoBlancoFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - RProd.png"))); // NOI18N
        getContentPane().add(FondoBlancoFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        FondoBlancoLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Lista - RProd.png"))); // NOI18N
        getContentPane().add(FondoBlancoLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 720, 940));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Azul.jpg"))); // NOI18N
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNombreProductoActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        Menu frame = new Menu();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegistrarActionPerformed
        
        String nombreProducto = JTFNombreProducto.getText();
        double precioVenta = Double.parseDouble(JTFPrecioVenta.getText());
        double cantidad = Double.parseDouble(JTFCantidad.getText());
        int fidMedida = JCBMedidas.getSelectedIndex() + 1;
        int fidMarca = JCBMarcas.getSelectedIndex() + 1;
      
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Productos (NombreProducto, PrecioVenta, Cantidad, FIDMedida, FIDMarca) VALUES (?, ?, ?, ?, ?)");
            ps.setString(1, nombreProducto);
            ps.setDouble(2, precioVenta);
            ps.setDouble(3, cantidad);
            ps.setInt(4, fidMedida);
            ps.setInt(5, fidMarca);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Guardado");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBRegistrarActionPerformed

    private void JTListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTListadoMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        try {
            int fila = JTListado.getSelectedRow();
            int id = Integer.parseInt(JTListado.getValueAt(fila, 0).toString());
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDProducto, NombreProducto, PrecioVenta, Cantidad, FIDMedida, FIDMarca FROM Productos WHERE IDProducto = ?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while(rs.next()){
                JTFIDProducto.setText(String.valueOf(id));
                JTFNombreProducto.setText(rs.getString("NombreProducto"));
                JTFPrecioVenta.setText(rs.getString("PrecioVenta"));
                JTFCantidad.setText(rs.getString("Cantidad"));
                JCBMedidas.setSelectedIndex(rs.getInt("FIDMedida") - 1);
                JCBMarcas.setSelectedIndex(rs.getInt("FIDMarca") - 1);
            }
            habilitarModificar();
            habilitarEliminar();
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_JTListadoMouseClicked

    private void JBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarActionPerformed
        int id = Integer.parseInt(JTFIDProducto.getText());
        String nombreProducto = JTFNombreProducto.getText();
        double precioVenta = Double.parseDouble(JTFPrecioVenta.getText());
        double cantidad = Double.parseDouble(JTFCantidad.getText());
        int fidMedida = JCBMedidas.getSelectedIndex() + 1;
        int fidMarca = JCBMarcas.getSelectedIndex() + 1;
      
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Productos SET NombreProducto = ?, PrecioVenta = ?, Cantidad = ?, FIDMedida = ?, FIDMarca = ? WHERE IDProducto = ?");
            ps.setString(1, nombreProducto);
            ps.setDouble(2, precioVenta);
            ps.setDouble(3, cantidad);
            ps.setInt(4, fidMedida);
            ps.setInt(5, fidMarca);
            ps.setInt(6, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Modificado");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBModificarActionPerformed

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        int id = Integer.parseInt(JTFIDProducto.getText());
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("DELETE FROM Productos WHERE IDProducto = ?");
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void JTFNombreProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreProductoKeyReleased
        habilitarRegistrar();
        habilitarModificar();
        habilitarEliminar();
    }//GEN-LAST:event_JTFNombreProductoKeyReleased

    private void JTFPrecioVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFPrecioVentaKeyReleased
        habilitarRegistrar();
        habilitarModificar();
        habilitarEliminar();
    }//GEN-LAST:event_JTFPrecioVentaKeyReleased

    private void JTFCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCantidadKeyReleased
        habilitarRegistrar();
        habilitarModificar();
        habilitarEliminar();
    }//GEN-LAST:event_JTFCantidadKeyReleased

    private void JTListadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTListadoKeyPressed
        //NO SIRVE
    }//GEN-LAST:event_JTListadoKeyPressed

    private void JTListadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTListadoKeyReleased
        
    }//GEN-LAST:event_JTListadoKeyReleased

    private void JBModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBModificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JBModificarMouseEntered

    private void JBModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBModificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JBModificarMouseExited

    private void JBAgregarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarMarcaActionPerformed
        Marcas agregarMarca = new Marcas();
        agregarMarca.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBAgregarMarcaActionPerformed

    private void JBMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMedidasActionPerformed
        UnidadesDeMedida agregarMedida = new UnidadesDeMedida();
        agregarMedida.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBMedidasActionPerformed

    private void JTFNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreProductoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c != ' ')) evt.consume();
    }//GEN-LAST:event_JTFNombreProductoKeyTyped

    private void JTFPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFPrecioVentaKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != ' ')) evt.consume();
    }//GEN-LAST:event_JTFPrecioVentaKeyTyped

    private void JTFCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCantidadKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c != ' ')) evt.consume();
    }//GEN-LAST:event_JTFCantidadKeyTyped

    private void limpiar() {
        JTFNombreProducto.setText("");
        JTFPrecioVenta.setText("");
        JTFCantidad.setText("");
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) JTListado.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDProducto, NombreProducto, PrecioVenta, Cantidad, Medida, Marca FROM Productos, Marcas, Medidas WHERE FIDMarca = IDMarca and FIDMEdida = IDMedida");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; ++i){
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void llenarComboBoxMarcas() {
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT Marca FROM Marcas");
            rs = ps.executeQuery();
            while(rs.next()){
                String marca = rs.getString("Marca");
                JCBMarcas.addItem(marca);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void llenarComboBoxMedidas() {
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT Medida FROM Medidas");
            rs = ps.executeQuery();
            while(rs.next()){
                String medida = rs.getString("Medida");
                JCBMedidas.addItem(medida);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoBlancoFormulario;
    private javax.swing.JLabel FondoBlancoLista;
    private javax.swing.JButton JBAgregarMarca;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBMedidas;
    private javax.swing.JButton JBModificar;
    private javax.swing.JButton JBRegistrar;
    private javax.swing.JComboBox<String> JCBMarcas;
    private javax.swing.JComboBox<String> JCBMedidas;
    private javax.swing.JTextField JTFCantidad;
    private javax.swing.JTextField JTFIDProducto;
    private javax.swing.JTextField JTFNombreProducto;
    private javax.swing.JTextField JTFPrecioVenta;
    private javax.swing.JTable JTListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
