/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author exbex
 */
public class ReporteInventario extends javax.swing.JFrame {

    /**
     * Creates new form ReporteInventario
     */
    public ReporteInventario() {
        initComponents();
        costoTotal();
        cantidadTotal();
        cargarTabla();
    }

    
    public void costoTotal() {
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT SUM(PrecioVenta) AS PrecioVenta FROM Productos");
            rs = ps.executeQuery();
            while (rs.next()) {
                costoTotal.setText(String.valueOf(rs.getInt("PrecioVenta")));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    public void cantidadTotal() {
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT SUM(Cantidad) AS Cantidad FROM Productos");
            rs = ps.executeQuery();
            while (rs.next()) {
                cantidadTotal.setText(String.valueOf(rs.getInt("Cantidad")));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) JTListado.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT DISTINCT(IDProducto) IDProducto, NombreProducto, Marca, Cantidad, PrecioVenta, Cantidad * PrecioVenta AS Importe FROM Productos, Marcas, Medidas WHERE FIDMarca = IDMarca");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; ++i){
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        costoTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListado = new javax.swing.JTable();
        JBImprimir = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel1.setText("Reporte de Inventario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 52, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel2.setText("Costo total del inventario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 135, -1, -1));

        costoTotal.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        costoTotal.setText("0.0");
        getContentPane().add(costoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 205, -1, -1));
        costoTotal.getAccessibleContext().setAccessibleParent(costoTotal);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        jLabel3.setText("Cantidad total de productos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 135, -1, -1));

        cantidadTotal.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        cantidadTotal.setText("0.0");
        getContentPane().add(cantidadTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 205, -1, -1));

        JTListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Marca", "Cantidad", "Precio de Venta", "Importe"
            }
        ));
        JTListado.setPreferredSize(new java.awt.Dimension(1246, 668));
        jScrollPane1.setViewportView(JTListado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 1320, 690));

        JBImprimir.setBackground(new java.awt.Color(20, 39, 78));
        JBImprimir.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        JBImprimir.setText("Imprimir");
        JBImprimir.setPreferredSize(new java.awt.Dimension(260, 120));
        JBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(JBImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 385, 260, 120));

        JBCancelar.setBackground(new java.awt.Color(215, 80, 56));
        JBCancelar.setFont(new java.awt.Font("Arial", 0, 35)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 575, 260, 120));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Reporte.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Azul.jpg"))); // NOI18N
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBImprimirActionPerformed
    JOptionPane.showMessageDialog(null, "Imprimiendo");
    }//GEN-LAST:event_JBImprimirActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBImprimir;
    private javax.swing.JTable JTListado;
    private javax.swing.JLabel cantidadTotal;
    private javax.swing.JLabel costoTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
