/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author exbex
 */
public class UnidadesDeMedida extends javax.swing.JFrame {

    /**
     * Creates new form UnidadesDeMedida
     */
    public UnidadesDeMedida() {
        initComponents();
        JTFIDMedida.setVisible(false);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTFIDMedida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JTFMedida = new javax.swing.JTextField();
        JBAgregar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBModificar = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTListado = new javax.swing.JTable();
        FondoBlancoLista = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTFIDMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIDMedidaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFIDMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1910, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        jLabel1.setText("Unidad de Medida:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 480, -1, -1));

        JTFMedida.setBackground(new java.awt.Color(155, 164, 180));
        JTFMedida.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        getContentPane().add(JTFMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 465, 500, 78));

        JBAgregar.setBackground(new java.awt.Color(20, 39, 78));
        JBAgregar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBAgregar.setText("Agregar");
        JBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1121, 592, 260, 120));

        JBCancelar.setBackground(new java.awt.Color(215, 80, 56));
        JBCancelar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1431, 592, 260, 120));

        JBModificar.setBackground(new java.awt.Color(57, 72, 103));
        JBModificar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBModificar.setText("Modificar");
        JBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBModificarActionPerformed(evt);
            }
        });
        getContentPane().add(JBModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 369, 260, 120));

        JBEliminar.setBackground(new java.awt.Color(204, 17, 17));
        JBEliminar.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(JBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 566, 260, 120));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 45)); // NOI18N
        jLabel2.setText("Registrar Unidad de Medida");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(921, 361, -1, -1));

        JTListado.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        JTListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTListado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 440, 690));

        FondoBlancoLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Lista - Medidas.png"))); // NOI18N
        getContentPane().add(FondoBlancoLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 155, -1, -1));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Blanco - Medidas.png"))); // NOI18N
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 315, -1, -1));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Azul.jpg"))); // NOI18N
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFIDMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIDMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIDMedidaActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        RegistroProductos rp = new RegistroProductos();
        rp.setVisible(true);
        dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarActionPerformed
        String medida = JTFMedida.getText();
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Medidas (Medida) VALUES (?)");
            ps.setString(1, medida);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Medida Guardado");
            limpiar();
            cargarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_JBAgregarActionPerformed

    private void JBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBModificarActionPerformed
        int id = Integer.parseInt(JTFIDMedida.getText());
        String medida = JTFMedida.getText();
      
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("UPDATE Medidas SET Medida = ? WHERE IDMedida = ?");
            ps.setString(1, medida);
            ps.setInt(2, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Medida Modificado");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBModificarActionPerformed

    private void JTListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTListadoMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        try {
            int fila = JTListado.getSelectedRow();
            int id = Integer.parseInt(JTListado.getValueAt(fila, 0).toString());
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDMedida, Medida FROM Medidas WHERE IDMedida = ?");
            ps.setInt(1, id);
            rs = ps.executeQuery();
            while(rs.next()){
                JTFIDMedida.setText(String.valueOf(id));
                JTFMedida.setText(rs.getString("Medida"));
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_JTListadoMouseClicked

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        int id = Integer.parseInt(JTFIDMedida.getText());
        
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement("DELETE FROM Medidas WHERE IDMedida = ?");
            ps.setInt(1, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Medida Eliminado");
            limpiar();
            cargarTabla();
        }catch(SQLException e) {
            System.out.print(e.toString());
        }
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void limpiar() {
        JTFMedida.setText("");
    }
    
    private void cargarTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) JTListado.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement("SELECT IDMedida, Medida FROM Medidas");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int i = 0; i < columnas; ++i){
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnidadesDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnidadesDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnidadesDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnidadesDeMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnidadesDeMedida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoBlancoLista;
    private javax.swing.JButton JBAgregar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JButton JBEliminar;
    private javax.swing.JButton JBModificar;
    private javax.swing.JTextField JTFIDMedida;
    private javax.swing.JTextField JTFMedida;
    private javax.swing.JTable JTListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
